name: "Build and Publish Packages"

on:
  push:
    branches:
      - commits_to_report_upstream*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

      - name: "Checking out"
        uses: actions/checkout@v4

      - name: "Setup java JDK"
        uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: temurin
          java-package: jdk
          cache: maven

      - name: "Publish package"
        run: |
          mvn -s settings.xml --batch-mode clean install deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
